#include "wrapper.h"

void init_wrapper_register(py::module_& m)
{
	//Implement module Register
	py::module mRegister = m.def_submodule("Register", "x64dbg Register python script wrapper");

	py::enum_<Register::RegisterEnum>(mRegister, "RegisterEnum")
		.value("DR0", Register::RegisterEnum::DR0)
		.value("DR1", Register::RegisterEnum::DR1)
		.value("DR2", Register::RegisterEnum::DR2)
		.value("DR3", Register::RegisterEnum::DR3)
		.value("DR6", Register::RegisterEnum::DR6)
		.value("DR7", Register::RegisterEnum::DR7)
		.value("EAX", Register::RegisterEnum::EAX)
		.value("AX", Register::RegisterEnum::AX)
		.value("AH", Register::RegisterEnum::AH)
		.value("AL", Register::RegisterEnum::AL)
		.value("EBX", Register::RegisterEnum::EBX)
		.value("BX", Register::RegisterEnum::BX)
		.value("BH", Register::RegisterEnum::BH)
		.value("BL", Register::RegisterEnum::BL)
		.value("ECX", Register::RegisterEnum::ECX)
		.value("CX", Register::RegisterEnum::CX)
		.value("CH", Register::RegisterEnum::CH)
		.value("CL", Register::RegisterEnum::CL)
		.value("EDX", Register::RegisterEnum::EDX)
		.value("DX", Register::RegisterEnum::DX)
		.value("DH", Register::RegisterEnum::DH)
		.value("DL", Register::RegisterEnum::DL)
		.value("EDI", Register::RegisterEnum::EDI)
		.value("DI", Register::RegisterEnum::DI)
		.value("ESI", Register::RegisterEnum::ESI)
		.value("SI", Register::RegisterEnum::SI)
		.value("EBP", Register::RegisterEnum::EBP)
		.value("BP", Register::RegisterEnum::BP)
		.value("ESP", Register::RegisterEnum::ESP)
		.value("SP", Register::RegisterEnum::SP)
		.value("EIP", Register::RegisterEnum::EIP)

#ifdef _WIN64
		.value("RAX", Register::RegisterEnum::RAX)
		.value("RBX", Register::RegisterEnum::RBX)
		.value("RCX", Register::RegisterEnum::RCX)
		.value("RDX", Register::RegisterEnum::RDX)
		.value("RSI", Register::RegisterEnum::RSI)
		.value("SIL", Register::RegisterEnum::SIL)
		.value("RDI", Register::RegisterEnum::RDI)
		.value("DIL", Register::RegisterEnum::DIL)
		.value("RBP", Register::RegisterEnum::RBP)
		.value("BPL", Register::RegisterEnum::BPL)
		.value("RSP", Register::RegisterEnum::RSP)
		.value("SPL", Register::RegisterEnum::SPL)
		.value("RIP", Register::RegisterEnum::RIP)
		.value("R8", Register::RegisterEnum::R8)
		.value("R8D", Register::RegisterEnum::R8D)
		.value("R8W", Register::RegisterEnum::R8W)
		.value("R8B", Register::RegisterEnum::R8B)
		.value("R9", Register::RegisterEnum::R9)
		.value("R9D", Register::RegisterEnum::R9D)
		.value("R9W", Register::RegisterEnum::R9W)
		.value("R9B", Register::RegisterEnum::R9B)
		.value("R10", Register::RegisterEnum::R10)
		.value("R10D", Register::RegisterEnum::R10D)
		.value("R10W", Register::RegisterEnum::R10W)
		.value("R10B", Register::RegisterEnum::R10B)
		.value("R11", Register::RegisterEnum::R11)
		.value("R11D", Register::RegisterEnum::R11D)
		.value("R11W", Register::RegisterEnum::R11W)
		.value("R11B", Register::RegisterEnum::R11B)
		.value("R12", Register::RegisterEnum::R12)
		.value("R12D", Register::RegisterEnum::R12D)
		.value("R12W", Register::RegisterEnum::R12W)
		.value("R12B", Register::RegisterEnum::R12B)
		.value("R13", Register::RegisterEnum::R13)
		.value("R13D", Register::RegisterEnum::R13D)
		.value("RR13W", Register::RegisterEnum::R13W)
		.value("R13B", Register::RegisterEnum::R13B)
		.value("R14", Register::RegisterEnum::R14)
		.value("R14D", Register::RegisterEnum::R14D)
		.value("R14W", Register::RegisterEnum::R14W)
		.value("R14B", Register::RegisterEnum::R14B)
		.value("R15", Register::RegisterEnum::R15)
		.value("R15D", Register::RegisterEnum::R15D)
		.value("R15W", Register::RegisterEnum::R15W)
		.value("R15B", Register::RegisterEnum::R15B)
#endif
		.value("CIP", Register::RegisterEnum::CIP)
		.value("CSP", Register::RegisterEnum::CSP)
		.value("CAX", Register::RegisterEnum::CAX)
		.value("CBX", Register::RegisterEnum::CBX)
		.value("CCX", Register::RegisterEnum::CCX)
		.value("CDX", Register::RegisterEnum::CDX)
		.value("CDI", Register::RegisterEnum::CDI)
		.value("CSI", Register::RegisterEnum::CSI)
		.value("CBP", Register::RegisterEnum::CBP)
		.value("CFLAGS", Register::RegisterEnum::CFLAGS);

	mRegister.def("Get", &Register::Get);
	mRegister.def("Set", &Register::Set);
	mRegister.def("Size", &Register::Size);
	mRegister.def("GetDR0", &Register::GetDR0);
	mRegister.def("SetDR0", &Register::SetDR0);
	mRegister.def("GetDR1", &Register::GetDR1);
	mRegister.def("SetDR1", &Register::SetDR1);
	mRegister.def("GetDR2", &Register::GetDR2);
	mRegister.def("SetDR2", &Register::SetDR2);
	mRegister.def("GetDR3", &Register::GetDR3);
	mRegister.def("SetDR3", &Register::SetDR3);
	mRegister.def("GetDR6", &Register::GetDR6);
	mRegister.def("SetDR6", &Register::SetDR6);
	mRegister.def("GetDR7", &Register::GetDR7);
	mRegister.def("SetDR7", &Register::SetDR7);
	mRegister.def("GetEAX", &Register::GetEAX);
	mRegister.def("SetEAX", &Register::SetEAX);
	mRegister.def("GetAX", &Register::GetAX);
	mRegister.def("SetAX", &Register::SetAX);
	mRegister.def("GetAH", &Register::GetAH);
	mRegister.def("SetAH", &Register::SetAH);
	mRegister.def("GetAL", &Register::GetAL);
	mRegister.def("SetAL", &Register::SetAL);
	mRegister.def("GetEBX", &Register::GetEBX);
	mRegister.def("SetEBX", &Register::SetEBX);
	mRegister.def("GetBX", &Register::GetBX);
	mRegister.def("SetBX", &Register::SetBX);
	mRegister.def("GetBH", &Register::GetBH);
	mRegister.def("SetBH", &Register::SetBH);
	mRegister.def("GetBL", &Register::GetBL);
	mRegister.def("SetBL", &Register::SetBL);
	mRegister.def("GetECX", &Register::GetECX);
	mRegister.def("SetECX", &Register::SetECX);
	mRegister.def("GetCX", &Register::GetCX);
	mRegister.def("SetCX", &Register::SetCX);
	mRegister.def("GetCH", &Register::GetCH);
	mRegister.def("SetCH", &Register::SetCH);
	mRegister.def("GetCL", &Register::GetCL);
	mRegister.def("SetCL", &Register::SetCL);
	mRegister.def("GetEDX", &Register::GetEDX);
	mRegister.def("SetEDX", &Register::SetEDX);
	mRegister.def("GetDX", &Register::GetDX);
	mRegister.def("SetDX", &Register::SetDX);
	mRegister.def("GetDH", &Register::GetDH);
	mRegister.def("SetDH", &Register::SetDH);
	mRegister.def("GetDL", &Register::GetDL);
	mRegister.def("SetDL", &Register::SetDL);
	mRegister.def("GetEDI", &Register::GetEDI);
	mRegister.def("SetEDI", &Register::SetEDI);
	mRegister.def("GetDI", &Register::GetDI);
	mRegister.def("SetDI", &Register::SetDI);
	mRegister.def("GetESI", &Register::GetESI);
	mRegister.def("SetESI", &Register::SetESI);
	mRegister.def("GetSI", &Register::GetSI);
	mRegister.def("SetSI", &Register::SetSI);
	mRegister.def("GetEBP", &Register::GetEBP);
	mRegister.def("SetEBP", &Register::SetEBP);
	mRegister.def("GetBP", &Register::GetBP);
	mRegister.def("SetBP", &Register::SetBP);
	mRegister.def("GetESP", &Register::GetESP);
	mRegister.def("SetESP", &Register::SetESP);
	mRegister.def("GetSP", &Register::GetSP);
	mRegister.def("SetSP", &Register::SetSP);
	mRegister.def("GetEIP", &Register::GetEIP);
	mRegister.def("SetEIP", &Register::SetEIP);

#ifdef _WIN64
	mRegister.def("GetRAX", &Register::GetRAX);
	mRegister.def("SetRAX", &Register::SetRAX);
	mRegister.def("GetRBX", &Register::GetRBX);
	mRegister.def("SetRBX", &Register::SetRBX);
	mRegister.def("GetRCX", &Register::GetRCX);
	mRegister.def("SetRCX", &Register::SetRCX);
	mRegister.def("GetRDX", &Register::GetRDX);
	mRegister.def("SetRDX", &Register::SetRDX);
	mRegister.def("GetRSI", &Register::GetRSI);
	mRegister.def("SetRSI", &Register::SetRSI);
	mRegister.def("GetSIL", &Register::GetSIL);
	mRegister.def("SetSIL", &Register::SetSIL);
	mRegister.def("GetRDI", &Register::GetRDI);
	mRegister.def("SetRDI", &Register::SetRDI);
	mRegister.def("GetDIL", &Register::GetDIL);
	mRegister.def("SetDIL", &Register::SetDIL);
	mRegister.def("GetRBP", &Register::GetRBP);
	mRegister.def("SetRBP", &Register::SetRBP);
	mRegister.def("GetBPL", &Register::GetBPL);
	mRegister.def("SetBPL", &Register::SetBPL);
	mRegister.def("GetRSP", &Register::GetRSP);
	mRegister.def("SetRSP", &Register::SetRSP);
	mRegister.def("GetSPL", &Register::GetSPL);
	mRegister.def("SetSPL", &Register::SetSPL);
	mRegister.def("GetRIP", &Register::GetRIP);
	mRegister.def("SetRIP", &Register::SetRIP);
	mRegister.def("GetR8", &Register::GetR8);
	mRegister.def("SetR8", &Register::SetR8);
	mRegister.def("GetR8D", &Register::GetR8D);
	mRegister.def("SetR8D", &Register::SetR8D);
	mRegister.def("GetR8W", &Register::GetR8W);
	mRegister.def("SetR8W", &Register::SetR8W);
	mRegister.def("GetR8B", &Register::GetR8B);
	mRegister.def("SetR8B", &Register::SetR8B);
	mRegister.def("GetR9", &Register::GetR9);
	mRegister.def("SetR9", &Register::SetR9);
	mRegister.def("GetR9D", &Register::GetR9D);
	mRegister.def("SetR9D", &Register::SetR9D);
	mRegister.def("GetR9W", &Register::GetR9W);
	mRegister.def("SetR9W", &Register::SetR9W);
	mRegister.def("GetR9B", &Register::GetR9B);
	mRegister.def("SetR9B", &Register::SetR9B);
	mRegister.def("GetR10", &Register::GetR10);
	mRegister.def("SetR10", &Register::SetR10);
	mRegister.def("GetR10D", &Register::GetR10D);
	mRegister.def("SetR10D", &Register::SetR10D);
	mRegister.def("GetR10W", &Register::GetR10W);
	mRegister.def("SetR10W", &Register::SetR10W);
	mRegister.def("GetR10B", &Register::GetR10B);
	mRegister.def("SetR10B", &Register::SetR10B);
	mRegister.def("GetR11", &Register::GetR11);
	mRegister.def("SetR11", &Register::SetR11);
	mRegister.def("GetR11D", &Register::GetR11D);
	mRegister.def("SetR11D", &Register::SetR11D);
	mRegister.def("GetR11W", &Register::GetR11W);
	mRegister.def("SetR11W", &Register::SetR11W);
	mRegister.def("GetR11B", &Register::GetR11B);
	mRegister.def("SetR11B", &Register::SetR11B);
	mRegister.def("GetR12", &Register::GetR12);
	mRegister.def("SetR12", &Register::SetR12);
	mRegister.def("GetR12D", &Register::GetR12D);
	mRegister.def("SetR12D", &Register::SetR12D);
	mRegister.def("GetR12W", &Register::GetR12W);
	mRegister.def("SetR12W", &Register::SetR12W);
	mRegister.def("GetR12B", &Register::GetR12B);
	mRegister.def("SetR12B", &Register::SetR12B);
	mRegister.def("GetR13", &Register::GetR13);
	mRegister.def("SetR13", &Register::SetR13);
	mRegister.def("GetR13D", &Register::GetR13D);
	mRegister.def("SetR13D", &Register::SetR13D);
	mRegister.def("GetR13W", &Register::GetR13W);
	mRegister.def("SetR13W", &Register::SetR13W);
	mRegister.def("GetR13B", &Register::GetR13B);
	mRegister.def("SetR13B", &Register::SetR13B);
	mRegister.def("GetR14", &Register::GetR14);
	mRegister.def("SetR14", &Register::SetR14);
	mRegister.def("GetR14D", &Register::GetR14D);
	mRegister.def("SetR14D", &Register::SetR14D);
	mRegister.def("GetR14W", &Register::GetR14W);
	mRegister.def("SetR14W", &Register::SetR14W);
	mRegister.def("GetR14B", &Register::GetR14B);
	mRegister.def("SetR14B", &Register::SetR14B);
	mRegister.def("GetR15", &Register::GetR15);
	mRegister.def("SetR15", &Register::SetR15);
	mRegister.def("GetR15D", &Register::GetR15D);
	mRegister.def("SetR15D", &Register::SetR15D);
	mRegister.def("GetR15W", &Register::GetR15W);
	mRegister.def("SetR15W", &Register::SetR15W);
	mRegister.def("GetR15B", &Register::GetR15B);
	mRegister.def("SetR15B", &Register::SetR15B);

#endif
	mRegister.def("GetCAX", &Register::GetCAX);
	mRegister.def("SetCAX", &Register::SetCAX);
	mRegister.def("GetCBX", &Register::GetCBX);
	mRegister.def("SetCBX", &Register::SetCBX);
	mRegister.def("GetCCX", &Register::GetCCX);
	mRegister.def("SetCCX", &Register::SetCCX);
	mRegister.def("GetCDX", &Register::GetCDX);
	mRegister.def("SetCDX", &Register::SetCDX);
	mRegister.def("GetCDI", &Register::GetCDI);
	mRegister.def("SetCDI", &Register::SetCDI);
	mRegister.def("GetCSI", &Register::GetCSI);
	mRegister.def("SetCSI", &Register::SetCSI);
	mRegister.def("GetCBP", &Register::GetCBP);
	mRegister.def("SetCBP", &Register::SetCBP);
	mRegister.def("GetCSP", &Register::GetCSP);
	mRegister.def("SetCSP", &Register::SetCSP);
	mRegister.def("GetCIP", &Register::GetCIP);
	mRegister.def("SetCIP", &Register::SetCIP);
	mRegister.def("GetCFLAGS", &Register::GetCFLAGS);
	mRegister.def("SetCFLAGS", &Register::SetCFLAGS);


}
